# -*- mode: yaml-*-
# vi: set ft=yaml sw=2 ts=2 :

- name: Prepare redis host
  hosts: all
  sudo: true
  gather_facts: no
  pre_tasks:
    - name: install python 2
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: false
    - name: gather facts when python2 is installed
      setup:
  tasks:
    - name: set locale
      lineinfile: dest=/etc/default/locale line="LC_ALL=C"
